from pysurveyjs.variables.variable import Variable
from pysurveyjs.variables.boolean_variable import BooleanVariable
from pysurveyjs.variables.numeric_variable import NumericVariable
from pysurveyjs.variables.string_variable import StringVariable